name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main 
    paths:
      - "store.html" 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload store.html to S3
        run: |
          aws s3 cp store.html s3://${{ secrets.S3_BUCKET_NAME }}/ --acl public-read
